name: example
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: gasd238/melon-ticket-actions@v1.1.0
        with:
          product-id: 209206
          schedule-id: 100001
          seat-id: 1
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
